server.port=8081
spring.application.name=endpointguard-demo-api
management.endpoints.web.exposure.include=health,info,metrics,prometheus,endpoint-stats
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
logging.level.com.endpointguard.demoapi=INFO
